# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    archive: 'puppet/archive'
    concat: 'puppetlabs/concat'
    systemd: 'camptocamp/systemd'
    stdlib: 'puppetlabs/stdlib'
