---
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '1.15.0'
Rakefile:
  changelog_user: 'grafana'
  changelog_project: 'puppet-promtail'
  changelog_version_tag_pattern: '%s'
  requires:
    - 'puppet-strings/tasks'
spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true

