FROM puppet/pdk:latest@sha256:515d467ccbf1cce98931fbcaa13cbd63d3cec4a7d9f69eb2382bd47e6bda4441

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

